//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspInANetStoreFrontEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CataloguedProduct
    {
        public int Id { get; set; }
        public int CatalogueId { get; set; }
        public int ProductId { get; set; }
    
        public virtual Catalogue Catalogue { get; set; }
        public virtual Product Product { get; set; }
    }
}
